In [46]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

ds = pd.read_csv("House Price India.csv")
ds.shape

(14619, 23)

In [25]:
ds.head


<bound method NDFrame.head of                id   Date  number of bedrooms  number of bathrooms  \
0      6762810635  42491                   4                 2.50   
1      6762810998  42491                   5                 2.75   
2      6762812605  42491                   4                 2.50   
3      6762812919  42491                   3                 2.00   
4      6762813105  42491                   3                 2.50   
...           ...    ...                 ...                  ...   
14614  6762830250  42734                   2                 1.50   
14615  6762830339  42734                   3                 2.00   
14616  6762830618  42734                   2                 1.00   
14617  6762830709  42734                   4                 1.00   
14618  6762831463  42734                   3                 1.00   

       living area  lot area  number of floors  waterfront present  \
0             2920      4000               1.5                   0   
1

In [28]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14619 entries, 0 to 14618
Data columns (total 23 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     14619 non-null  int64  
 1   Date                                   14619 non-null  int64  
 2   number of bedrooms                     14619 non-null  int64  
 3   number of bathrooms                    14619 non-null  float64
 4   living area                            14619 non-null  int64  
 5   lot area                               14619 non-null  int64  
 6   number of floors                       14619 non-null  float64
 7   waterfront present                     14619 non-null  int64  
 8   number of views                        14619 non-null  int64  
 9   condition of the house                 14619 non-null  int64  
 10  grade of the house                     14619 non-null  int64  
 11  Ar

In [30]:
ds.isnull().sum()

id                                       0
Date                                     0
number of bedrooms                       0
number of bathrooms                      0
living area                              0
lot area                                 0
number of floors                         0
waterfront present                       0
number of views                          0
condition of the house                   0
grade of the house                       0
Area of the house(excluding basement)    0
Area of the basement                     0
Built Year                               0
Renovation Year                          0
Postal Code                              0
Lattitude                                0
Longitude                                0
living_area_renov                        0
lot_area_renov                           0
Number of schools nearby                 0
Distance from the airport                0
Price                                    0
dtype: int6

In [32]:
ds.dropna()

id   Date  number of bedrooms  number of bathrooms  \
0      6762810635  42491                   4                 2.50   
1      6762810998  42491                   5                 2.75   
2      6762812605  42491                   4                 2.50   
3      6762812919  42491                   3                 2.00   
4      6762813105  42491                   3                 2.50   
...           ...    ...                 ...                  ...   
14614  6762830250  42734                   2                 1.50   
14615  6762830339  42734                   3                 2.00   
14616  6762830618  42734                   2                 1.00   
14617  6762830709  42734                   4                 1.00   
14618  6762831463  42734                   3                 1.00   

       living area  lot area  number of floors  waterfront present  \
0             2920      4000               1.5                   0   
1             2910      9480               1.5                   0   
2             3310     42998               2.0                   0   
3             2710      4500               1.5                   0   
4             2600      4750               1.0                   0   
...            ...       ...               ...                 ...   
14614         1556     20000               1.0                   0   
14615         1680      7000               1.5                   0   
14616         1070      6120               1.0                   0   
14617         1030      6621               1.0                   0   
14618          900      4770               1.0                   0   

       number of views  condition of the house  ...  Built Year  \
0                    0                       5  ...        1909   
1                    0                       3  ...        1939   
2                    0                       3  ...        2001   
3                    0                       4  ...        1929   
4                    0                       4  ...        1951   
...                ...                     ...  ...         ...   
14614                0                       4  ...        1957   
14615                0                       4  ...        1968   
14616                0                       3  ...        1962   
14617                0                       4  ...        1955   
14618                0                       3  ...        1969   

       Renovation Year  Postal Code  Lattitude  Longitude  living_area_renov  \
0                    0       122004    52.8878   -114.470               2470   
1                    0       122004    52.8852   -114.468               2940   
2                    0       122005    52.9532   -114.321               3350   
3                    0       122006    52.9047   -114.485               2060   
4                    0       122007    52.9133   -114.590               2380   
...                ...          ...        ...        ...                ...   
14614                0       122066    52.6191   -114.472               2250   
14615                0       122072    52.5075   -114.393               1540   
14616                0       122056    52.7289   -114.507               1130   
14617                0       122042    52.7157   -114.411               1420   
14618             2009       122018    52.5338   -114.552                900   

       lot_area_renov  Number of schools nearby  Distance from the airport  \
0                4000                         2                         51   
1                6600                         1                         53   
2               42847                         3                         76   
3                4500                         1                         51   
4                4750                         1                         67   
...               ...                       ...                        ...   
14614           17286            

In [40]:
f = ['number of bedrooms','number of bathrooms','living area','lot area','number of floors','condition of the house','Built Year','Distance from the airport','Number of schools nearby']
a = ds[f]
b = ds['Price']

In [54]:
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(a_train, b_train)


LinearRegression()

In [56]:
b_pred = model.predict(a_test)

print("R^2 Score:", r2_score(b_test, b_pred))
print("Mean Squared Error:", mean_squared_error(b_test, b_pred))


R^2 Score: 0.5904552146987075
Mean Squared Error: 60611019364.87399


In [60]:
sample = np.array([[5, 2, 3, 8000, 2, 5,2005,55,1]])  # Example input
predicted_price = model.predict(sample)
print("Predicted House Price: $", predicted_price[0])


Predicted House Price: $ -250676.16740689706


In [64]:


def get_matrix(prompt):
    r = int(input(f"Enter rows for {prompt}: "))
    c = int(input(f"Enter columns for {prompt}: "))
    print(f"Enter elements for {prompt} row-wise:")
    elements = list(map(float, input().split()))
    return np.array(elements).reshape(r, c)

def matrix_operations():
    while True:
        print("\nMatrix Operations Menu:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Transpose")
        print("5. Determinant")
        print("6. Exit")
        choice = input("Choose an option (1-6): ")

        if choice in ['1', '2', '3']:
            A = get_matrix("Matrix A")
            B = get_matrix("Matrix B")
            if A.shape != B.shape and choice in ['1', '2']:
                print("Matrix dimensions must be same for addition/subtraction.")
                continue
            if choice == '1':
                print("Result:\n", A + B)
            elif choice == '2':
                print("Result:\n", A - B)
            elif choice == '3':
                if A.shape[1] != B.shape[0]:
                    print("Invalid dimensions for multiplication.")
                else:
                    print("Result:\n", A @ B)

        elif choice == '4':
            A = get_matrix("Matrix")
            print("Transpose:\n", A.T)

        elif choice == '5':
            A = get_matrix("Square Matrix")
            if A.shape[0] != A.shape[1]:
                print("Determinant requires a square matrix.")
            else:
                print("Determinant:", np.linalg.det(A))

        elif choice == '6':
            print("Exiting Matrix Operations Tool.")
            break

        else:
            print("Invalid choice. Try again.")

matrix_operations()



Matrix Operations Menu:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit


Choose an option (1-6):  1
Enter rows for Matrix A:  2
Enter columns for Matrix A:  2


Enter elements for Matrix A row-wise:


 1 2 3 4
Enter rows for Matrix B:  2
Enter columns for Matrix B:  2


Enter elements for Matrix B row-wise:


 1 2 3 4


Result:
 [[2. 4.]
 [6. 8.]]

Matrix Operations Menu:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit


Choose an option (1-6):  2
Enter rows for Matrix A:  2
Enter columns for Matrix A:  2


Enter elements for Matrix A row-wise:


 3 4 2 7
Enter rows for Matrix B:  2
Enter columns for Matrix B:  2


Enter elements for Matrix B row-wise:


 1 7 5 4


Result:
 [[ 2. -3.]
 [-3.  3.]]

Matrix Operations Menu:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit


Choose an option (1-6):  3
Enter rows for Matrix A:  2
Enter columns for Matrix A:  2


Enter elements for Matrix A row-wise:


 2 3 5 1
Enter rows for Matrix B:  2 
Enter columns for Matrix B:  2


Enter elements for Matrix B row-wise:


 7 6 4 3


Result:
 [[26. 21.]
 [39. 33.]]

Matrix Operations Menu:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit


Choose an option (1-6):  5
Enter rows for Square Matrix:  1 2 3 4 5 6


ValueError: invalid literal for int() with base 10: '1 2 3 4 5 6'

In [66]:

def get_matrix(prompt):
    r = int(input(f"Enter rows for {prompt}: "))
    c = int(input(f"Enter columns for {prompt}: "))
    print(f"Enter elements for {prompt} row-wise:")
    elements = list(map(float, input().split()))
    return np.array(elements).reshape(r, c)

def matrix_operations():
    while True:
        print("\nMatrix Operations Menu:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Transpose")
        print("5. Determinant")
        print("6. Exit")
        choice = input("Choose an option (1-6): ")

        if choice in ['1', '2', '3']:
            A = get_matrix("Matrix A")
            B = get_matrix("Matrix B")
            if A.shape != B.shape and choice in ['1', '2']:
                print("Matrix dimensions must be same for addition/subtraction.")
                continue
            if choice == '1':
                print("Result:\n", A + B)
            elif choice == '2':
                print("Result:\n", A - B)
            elif choice == '3':
                if A.shape[1] != B.shape[0]:
                    print("Invalid dimensions for multiplication.")
                else:
                    print("Result:\n", A @ B)

        elif choice == '4':
            A = get_matrix("Matrix")
            print("Transpose:\n", A.T)

        elif choice == '5':
            A = get_matrix("Square Matrix")
            if A.shape[0] != A.shape[1]:
                print("Determinant requires a square matrix.")
            else:
                print("Determinant:", np.linalg.det(A))

        elif choice == '6':
            print("Exiting Matrix Operations Tool.")
            break

        else:
            print("Invalid choice. Try again.")

matrix_operations()


Matrix Operations Menu:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit


Choose an option (1-6):  5
Enter rows for Square Matrix:  2
Enter columns for Square Matrix:  2


Enter elements for Square Matrix row-wise:


 1 2 3 4


Determinant: -2.0000000000000004

Matrix Operations Menu:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit


Choose an option (1-6):  6


Exiting Matrix Operations Tool.
