In [1]:
import numpy as np

def input_matrix(name):
    rows = int(input(f"Enter number of rows for matrix {name}: "))
    cols = int(input(f"Enter number of columns for matrix {name}: "))
    print(f"Enter elements of matrix {name} row by row (space-separated):")
    elements = []
    for i in range(rows):
        row = list(map(int, input(f"{name} Row {i+1}: ").split()))
        elements.append(row)
    return np.array(elements)
A = input_matrix('A')
B = input_matrix('B')


print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", np.dot(A, B))
print("Transpose A:\n", A.T)
print("Determinant A:", np.linalg.det(A))  

while True:
    print("\nChoose an operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Transpose of A")
    print("5. Determinant of A")
    print("6. Exit")

    choice = int(input("Enter your choice: "))

           
    if choice == 1:
        if A.shape == B.shape:
            print("Addition:\n", A + B)
        else:
            print("Error: Matrices must be the same shape for addition.")

    elif choice == 2:
        if A.shape == B.shape:
            print("Subtraction:\n", A - B)
        else:
            print("Error: Matrices must be the same shape for subtraction.")

    elif choice == 3:
        if A.shape[1] == B.shape[0]:
            print("Multiplication:\n", np.dot(A, B))
        else:
            print("Error: Matrix A columns must match Matrix B rows.")

    elif choice == 4:
        print("Transpose of A:\n", A.T)

    elif choice == 5:
        if A.shape[0] == A.shape[1]:
            print("Determinant of A:", np.linalg.det(A))
        else:
            print("Error: Determinant only defined for square matrices.")

    elif choice == 6:
        print("Exiting...")
        break

    else:
        print("Invalid choice. Try again.")

Enter number of rows for matrix A:  2
Enter number of columns for matrix A:  2


Enter elements of matrix A row by row (space-separated):


A Row 1:  1 2
A Row 2:  2 3
Enter number of rows for matrix B:  2
Enter number of columns for matrix B:  2


Enter elements of matrix B row by row (space-separated):


B Row 1:  3 4 
B Row 2:  5 7


Addition:
 [[ 4  6]
 [ 7 10]]
Subtraction:
 [[-2 -2]
 [-3 -4]]
Multiplication:
 [[13 18]
 [21 29]]
Transpose A:
 [[1 2]
 [2 3]]
Determinant A: -1.0

Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose of A
5. Determinant of A
6. Exit


Enter your choice:  1


Addition:
 [[ 4  6]
 [ 7 10]]

Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose of A
5. Determinant of A
6. Exit


Enter your choice:  2


Subtraction:
 [[-2 -2]
 [-3 -4]]

Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose of A
5. Determinant of A
6. Exit


Enter your choice:  3


Multiplication:
 [[13 18]
 [21 29]]

Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose of A
5. Determinant of A
6. Exit


Enter your choice:  4


Transpose of A:
 [[1 2]
 [2 3]]

Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose of A
5. Determinant of A
6. Exit


Enter your choice:  5


Determinant of A: -1.0

Choose an operation:
1. Addition
2. Subtraction
3. Multiplication
4. Transpose of A
5. Determinant of A
6. Exit


Enter your choice:  6


Exiting...
